[package]
name = "bevy_asset_preload"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy_app = "0.12.0"
bevy_asset = "0.12.0"
bevy_ecs = "0.12.0"
wasm_load = {path = "wasm_load"}

[workspace]
members = [
    "wasm_load"
]