[package]
name = "bevy_asset_preload"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy_app = "0.15.0"
bevy_asset = "0.15.0"
bevy_ecs = "0.15.0"
bevy_state = "0.15.0"
load_assets = {path = "load_assets" }

[workspace]
members = [
    "load_assets"
]